export { default as Footer } from "./Footer";
export { default as Layout } from "./Layout";
export { default as Navbar } from "./Navbar";
export { default as Products } from "./Products";
export { default as FooterBanner } from "./FooterBanner";
export { default as Contact } from "./Contact";
export { default as Cart } from "./Cart";
export { default as Slider } from "./Slider";
export { default as Products2 } from "./Products2";
